name: kernel_uq
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.5.0=h27087fc_0
  - aws-c-auth=0.7.22=hf36ad8f_6
  - aws-c-cal=0.6.15=h816f305_1
  - aws-c-common=0.9.23=h4ab18f5_0
  - aws-c-compression=0.2.18=he027950_7
  - aws-c-event-stream=0.4.2=hb72ac1a_14
  - aws-c-http=0.8.2=h75ac8c9_3
  - aws-c-io=0.14.9=hd3d3696_3
  - aws-c-mqtt=0.10.4=hb0abfc5_7
  - aws-c-s3=0.5.10=h44b787d_4
  - aws-c-sdkutils=0.1.16=he027950_3
  - aws-checksums=0.1.18=he027950_7
  - aws-crt-cpp=0.26.12=he940a02_1
  - aws-sdk-cpp=1.11.329=h0f5bab0_6
  - blas=1.0=mkl
  - blosc=1.21.6=hef167b5_0
  - bokeh=3.7.3=pyhd8ed1ab_0
  - bottleneck=1.5.0=py311h9f3472d_0
  - brotli-python=1.1.0=py311hfdbb021_3
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cairo=1.16.0=h35add3b_1015
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - cftime=1.6.4=py311h9f3472d_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.3=py311hdf67eae_1
  - cpython=3.11.13=py311hd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - cytoolz=1.0.1=py311h9ecbd09_0
  - dask=2025.7.0=pyhe01879c_0
  - dask-core=2025.7.0=pyhe01879c_1
  - dav1d=1.2.1=h5eee18b_0
  - distributed=2025.7.0=pyhe01879c_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.4.2=gpl_h8dda1f0_112
  - filelock=3.18.0=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.13.3=ha770c72_1
  - fribidi=1.0.10=h7b6447c_0
  - fsspec=2025.7.0=pyhd8ed1ab_0
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=h5eee18b_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h0f6cedb_0
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=h295c915_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=7.3.0=hdb3a94d_0
  - hdf4=4.2.15=h9772cbc_5
  - hdf5=1.14.3=nompi_h2d575fe_109
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=72.1=hcb278e6_0
  - idna=3.10=pyhd8ed1ab_1
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2022.0.1=h06a4308_3633
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jpeg=9e=h5eee18b_3
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.4=h3f801dc_0
  - libarrow=16.1.0=h9102155_9_cpu
  - libarrow-acero=16.1.0=hac33072_9_cpu
  - libarrow-dataset=16.1.0=hac33072_9_cpu
  - libarrow-substrait=16.1.0=h7e0c224_9_cpu
  - libavif=0.11.1=h8182462_2
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_3
  - libbrotlidec=1.1.0=hb9d3cd8_3
  - libbrotlienc=1.1.0=hb9d3cd8_3
  - libcblas=3.9.0=16_linux64_mkl
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.1.3=0
  - libcurand=10.3.5.147=0
  - libcurl=8.14.1=h332b0f4_0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.17=h0b41bf4_0
  - libdrm=2.4.125=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_4
  - libgcc-ng=15.1.0=h69a702a_4
  - libgfortran=15.1.0=h69a702a_4
  - libgfortran5=15.1.0=hcea5267_4
  - libglib=2.84.0=h2ff4ddf_0
  - libgomp=15.1.0=h767d61c_4
  - libgoogle-cloud=2.25.0=h2736e30_0
  - libgoogle-cloud-storage=2.25.0=h3d9a0c8_0
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnetcdf=4.9.2=nompi_h80fb2b6_112
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hb9d3cd8_1
  - libnvjpeg=11.9.0.86=0
  - libparquet=16.1.0=h6a7eafb_9_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libprotobuf=4.25.3=hd5b35b9_1
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_4
  - libstdcxx-ng=15.1.0=h4852527_4
  - libtasn1=4.19.0=h5eee18b_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.5.0=h6adf6a1_2
  - libunistring=0.9.10=h27cfd23_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.18.0=h0b41bf4_0
  - libvpx=1.11.0=h9c3ff4c_3
  - libwebp=1.2.4=h1daa5a0_1
  - libwebp-base=1.2.4=h166bdaf_0
  - libxcb=1.13=h7f98852_1004
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.11.5=h0d562d8_0
  - libzip=1.11.2=h6991a6a_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lightning-utilities=0.15.2=pyhd8ed1ab_0
  - llvm-openmp=12.0.1=h4bd325d_1
  - locket=1.0.0=pyhd8ed1ab_0
  - lz4=4.3.3=py311h2cbdf9a_1
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_1
  - msgpack-python=1.1.1=py311hd18a35c_0
  - narwhals=2.1.1=pyhe01879c_0
  - ncurses=6.5=h7934f7d_0
  - netcdf4=1.7.2=nompi_py311hae66bec_101
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.5=pyhe01879c_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.5.2=h26f9b46_0
  - orc=2.0.1=h17fec99_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.1=py311hed34c8f_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.44=hc749103_2
  - pillow=9.4.0=py311h50def17_1
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - psutil=7.0.0=py311h9ecbd09_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyarrow=16.1.0=py311hbd00459_4
  - pyarrow-core=16.1.0=py311h8c3dac4_4_cpu
  - pycparser=2.22=pyh29332c3_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h9e4cc4f_2_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=2_cp311
  - pytorch=2.5.1=py3.11_cuda11.8_cudnn9.1.0_0
  - pytorch-cuda=11.8=h7e8668a_6
  - pytorch-lightning=2.5.3=pyh2a12c56_0
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - re2=2023.09.01=h7f4b329_2
  - readline=8.3=hc2a1206_0
  - requests=2.32.4=pyhd8ed1ab_0
  - s2n=1.4.16=he19d79f_0
  - setuptools=78.1.1=py311h06a4308_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - sqlite=3.50.4=hbc0de68_0
  - svt-av1=1.4.1=hcb278e6_0
  - tblib=3.1.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - toolz=1.0.0=pyhd8ed1ab_1
  - torchaudio=2.5.1=py311_cu118
  - torchmetrics=1.8.1=pyhd8ed1ab_0
  - torchtriton=3.1.0=py311
  - torchvision=0.20.1=py311_cu118
  - tornado=6.5.2=py311h49ec1c0_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.14.1=h4440ef1_0
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311h06a4308_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xarray=2025.7.1=pyhd8ed1ab_0
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.4=h0b41bf4_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.10=h7f98852_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xyzservices=2025.4.0=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml=0.2.5=h280c20c_3
  - zict=3.0.0=pyhd8ed1ab_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py311h9ecbd09_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aenum==3.1.16
      - affine==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asdfghjkl==0.1a4
      - asttokens==3.0.0
      - attrs==25.3.0
      - backpack-for-pytorch==1.7.1
      - bitsandbytes==0.47.0
      - cartopy==0.25.0
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cmcrameri==1.9
      - comm==0.2.3
      - crc32c==2.7.1
      - curvlinops-for-pytorch==2.0.1
      - cycler==0.12.1
      - debugpy==1.8.16
      - decorator==5.2.1
      - docstring-parser==0.17.0
      - donfig==0.8.1.post1
      - einconv==0.1.0
      - einops==0.8.1
      - ema-pytorch==0.7.7
      - et-xmlfile==2.0.0
      - executing==2.2.0
      - fiona==1.10.1
      - fonttools==4.59.0
      - frozenlist==1.7.0
      - geographiclib==2.0
      - geopy==2.4.1
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gpytorch==1.14
      - h5py==3.14.0
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - hydra-core==1.3.2
      - importlib-resources==6.5.2
      - ipykernel==6.30.1
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - jaxtyping==0.3.2
      - jedi==0.19.2
      - joblib==1.5.1
      - jsonargparse==4.40.2
      - jsonnet==0.21.0
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - kiwisolver==1.4.9
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - laplace-torch==0.2.2.2
      - lightly==1.5.22
      - lightly-utils==0.0.2
      - lightning==2.5.3
      - lightning-uq-box==0.3.0.dev0
      - linear-operator==0.6
      - markdown-it-py==4.0.0
      - matplotlib==3.10.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - multidict==6.6.4
      - nest-asyncio==1.6.0
      - numcodecs==0.16.2
      - numpy==1.26.4
      - omegaconf==2.3.0
      - openpyxl==3.1.5
      - opt-einsum==3.4.0
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.8
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.31.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyproj==3.7.2
      - pyshp==2.3.1
      - pyzmq==27.0.1
      - rasterio==1.4.3
      - rich==14.1.0
      - rtree==1.4.1
      - safetensors==0.6.2
      - scienceplots==2.1.1
      - scikit-learn==1.7.1
      - scipy==1.16.1
      - scoringrules==0.8.0
      - segmentation-models-pytorch==0.5.0
      - sentry-sdk==2.34.1
      - shapely==2.1.1
      - smmap==5.0.2
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - timm==1.0.19
      - torch-geometric==2.6.1
      - torchgeo==0.7.1
      - torchseg==0.0.1a4
      - traitlets==5.14.3
      - typeshed-client==2.8.2
      - typing-inspection==0.4.1
      - uncertainty-toolbox==0.1.1
      - unfoldnd==0.2.3
      - wadler-lindig==0.1.7
      - wandb==0.21.1
      - wcwidth==0.2.13
      - xlrd==2.0.2
      - yarl==1.20.1
      - zarr==3.1.1
prefix: anaconda3/envs/kernel_uq
